development: &default
  adapter: postgresql
  database: hello_zoo_development
  encoding: utf8
  min_messages: warning
  host: localhost
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: hello_zoo_test

production:
  <<: *default
  database: hello_zoo_production
